name: junco-env
dependencies:
- python=3
- numpy
- scipy
- cvxopt
- pip
- matplotlib
- ipykernel
- pip:
  # works for regular pip packages
  - gym
  - git+https://github.com/python-control/python-control.git
